name: Collect videos

on:
  workflow_dispatch:
  schedule:
  - cron: '0 9 * * *'
    
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: 'npm'
    - run: npm ci
    - run: npx nodejsscript crawler.js
      env:
        YOUTUBE_TOKEN: ${{ secrets.YOUTUBE_TOKEN }}
