name: Notifications
permissions: {}
on:
  workflow_dispatch:
  schedule:
  - cron: '53 15,16 * * *'
env:
  TZ: "Europe/Prague"
  LOCAL_HOUR: "17"
jobs:
  cron-local:
    # Usage:
    # 1) sets env:
    #   env:
    #     TZ: "Europe/Prague"
    #     LOCAL_HOUR: "08"
    # 2) in job
    #    if: needs.cron-local.outputs.isRunTime == 'True'
    #    needs: cron-local
    runs-on: ubuntu-latest
    outputs:
      isRunTime: ${{ steps.check_local_time.outputs.isRunTime }}
    steps:
      - name: Check local time
        id: check_local_time
        run: |
          isRunTime=False
          if [[ ${TRIGGER} != 'schedule' ]]; then
            isRunTime=True
          elif [ $(date --date='now' +%H) -eq $LOCAL_HOUR ]; then 
            isRunTime=True
          fi
          echo "$isRunTime"
          echo "isRunTime=$isRunTime" >> "$GITHUB_OUTPUT"
        env:
          TRIGGER: ${{ github.event_name }}
  main:
    runs-on: ubuntu-latest
    if: needs.cron-local.outputs.isRunTime == 'True'
    needs: cron-local
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version: lts/*
        cache: 'npm'
    - run: npm ci
    - run: |
        if [ $(date --date='now' +%w) -eq '5' ]; then 
          npx nodejsscript crawler.js &&
          npx nodejsscript index.js mastodon --only 'Zpátky mimo téma'
        fi
        npx nodejsscript notifications.js mastodon --old 24
      env:
        YOUTUBE_TOKEN: ${{ secrets.YOUTUBE_TOKEN }}
        MASTODON_URL: https://mastodonczech.cz/
        MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
